/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AuthIndexRouteImport } from './routes/_auth/index'
import { Route as AuthChecklistsRouteRouteImport } from './routes/_auth/checklists/route'
import { Route as AuthChecklistsIndexRouteImport } from './routes/_auth/checklists/index'
import { Route as AuthChecklistsCreateIndexRouteImport } from './routes/_auth/checklists/create/index'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthChecklistsRouteRoute = AuthChecklistsRouteRouteImport.update({
  id: '/checklists',
  path: '/checklists',
  getParentRoute: () => AuthRoute,
} as any)
const AuthChecklistsIndexRoute = AuthChecklistsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthChecklistsRouteRoute,
} as any)
const AuthChecklistsCreateIndexRoute =
  AuthChecklistsCreateIndexRouteImport.update({
    id: '/create/',
    path: '/create/',
    getParentRoute: () => AuthChecklistsRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthIndexRoute
  '/login': typeof LoginRoute
  '/checklists': typeof AuthChecklistsRouteRouteWithChildren
  '/checklists/': typeof AuthChecklistsIndexRoute
  '/checklists/create/': typeof AuthChecklistsCreateIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/': typeof AuthIndexRoute
  '/checklists': typeof AuthChecklistsIndexRoute
  '/checklists/create': typeof AuthChecklistsCreateIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/_auth/checklists': typeof AuthChecklistsRouteRouteWithChildren
  '/_auth/': typeof AuthIndexRoute
  '/_auth/checklists/': typeof AuthChecklistsIndexRoute
  '/_auth/checklists/create/': typeof AuthChecklistsCreateIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/checklists'
    | '/checklists/'
    | '/checklists/create/'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/' | '/checklists' | '/checklists/create'
  id:
    | '__root__'
    | '/_auth'
    | '/login'
    | '/_auth/checklists'
    | '/_auth/'
    | '/_auth/checklists/'
    | '/_auth/checklists/create/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/checklists': {
      id: '/_auth/checklists'
      path: '/checklists'
      fullPath: '/checklists'
      preLoaderRoute: typeof AuthChecklistsRouteRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/checklists/': {
      id: '/_auth/checklists/'
      path: '/'
      fullPath: '/checklists/'
      preLoaderRoute: typeof AuthChecklistsIndexRouteImport
      parentRoute: typeof AuthChecklistsRouteRoute
    }
    '/_auth/checklists/create/': {
      id: '/_auth/checklists/create/'
      path: '/create'
      fullPath: '/checklists/create/'
      preLoaderRoute: typeof AuthChecklistsCreateIndexRouteImport
      parentRoute: typeof AuthChecklistsRouteRoute
    }
  }
}

interface AuthChecklistsRouteRouteChildren {
  AuthChecklistsIndexRoute: typeof AuthChecklistsIndexRoute
  AuthChecklistsCreateIndexRoute: typeof AuthChecklistsCreateIndexRoute
}

const AuthChecklistsRouteRouteChildren: AuthChecklistsRouteRouteChildren = {
  AuthChecklistsIndexRoute: AuthChecklistsIndexRoute,
  AuthChecklistsCreateIndexRoute: AuthChecklistsCreateIndexRoute,
}

const AuthChecklistsRouteRouteWithChildren =
  AuthChecklistsRouteRoute._addFileChildren(AuthChecklistsRouteRouteChildren)

interface AuthRouteChildren {
  AuthChecklistsRouteRoute: typeof AuthChecklistsRouteRouteWithChildren
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthChecklistsRouteRoute: AuthChecklistsRouteRouteWithChildren,
  AuthIndexRoute: AuthIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
