/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/public'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AuthIndexRouteImport } from './routes/_auth/index'
import { Route as AuthPropertiesRouteRouteImport } from './routes/_auth/properties/route'
import { Route as AuthPersonsRouteRouteImport } from './routes/_auth/persons/route'
import { Route as AuthChecklistsRouteRouteImport } from './routes/_auth/checklists/route'
import { Route as AuthUsersIndexRouteImport } from './routes/_auth/users/index'
import { Route as AuthPropertiesIndexRouteImport } from './routes/_auth/properties/index'
import { Route as AuthChecklistsIndexRouteImport } from './routes/_auth/checklists/index'
import { Route as AuthAccountIndexRouteImport } from './routes/_auth/account/index'
import { Route as AuthPersonsCreateRouteImport } from './routes/_auth/persons/create'
import { Route as AuthPropertiesPropertyIdRouteRouteImport } from './routes/_auth/properties/$propertyId/route'
import { Route as AuthChecklistsChecklistIdRouteRouteImport } from './routes/_auth/checklists/$checklistId/route'
import { Route as AuthUsersUserIdIndexRouteImport } from './routes/_auth/users/$userId/index'
import { Route as AuthPropertiesCreateIndexRouteImport } from './routes/_auth/properties/create/index'
import { Route as AuthPropertiesPropertyIdIndexRouteImport } from './routes/_auth/properties/$propertyId/index'
import { Route as AuthChecklistsCreateIndexRouteImport } from './routes/_auth/checklists/create/index'
import { Route as AuthChecklistsChecklistIdItemsRouteRouteImport } from './routes/_auth/checklists/$checklistId/items/route'
import { Route as AuthUsersUserIdEditIndexRouteImport } from './routes/_auth/users/$userId/edit/index'
import { Route as AuthPropertiesPropertyIdEditIndexRouteImport } from './routes/_auth/properties/$propertyId/edit/index'
import { Route as AuthChecklistsChecklistIdItemsIndexRouteImport } from './routes/_auth/checklists/$checklistId/items/index'
import { Route as AuthChecklistsChecklistIdHistoryIndexRouteImport } from './routes/_auth/checklists/$checklistId/history/index'
import { Route as AuthChecklistsChecklistIdItemsItemIdRouteRouteImport } from './routes/_auth/checklists/$checklistId/items/$itemId/route'
import { Route as AuthChecklistsChecklistIdItemsItemIdIndexRouteImport } from './routes/_auth/checklists/$checklistId/items/$itemId/index'

const PublicRoute = PublicRouteImport.update({
  id: '/public',
  path: '/public',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthPropertiesRouteRoute = AuthPropertiesRouteRouteImport.update({
  id: '/properties',
  path: '/properties',
  getParentRoute: () => AuthRoute,
} as any)
const AuthPersonsRouteRoute = AuthPersonsRouteRouteImport.update({
  id: '/persons',
  path: '/persons',
  getParentRoute: () => AuthRoute,
} as any)
const AuthChecklistsRouteRoute = AuthChecklistsRouteRouteImport.update({
  id: '/checklists',
  path: '/checklists',
  getParentRoute: () => AuthRoute,
} as any)
const AuthUsersIndexRoute = AuthUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthPropertiesIndexRoute = AuthPropertiesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthPropertiesRouteRoute,
} as any)
const AuthChecklistsIndexRoute = AuthChecklistsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthChecklistsRouteRoute,
} as any)
const AuthAccountIndexRoute = AuthAccountIndexRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthPersonsCreateRoute = AuthPersonsCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AuthPersonsRouteRoute,
} as any)
const AuthPropertiesPropertyIdRouteRoute =
  AuthPropertiesPropertyIdRouteRouteImport.update({
    id: '/$propertyId',
    path: '/$propertyId',
    getParentRoute: () => AuthPropertiesRouteRoute,
  } as any)
const AuthChecklistsChecklistIdRouteRoute =
  AuthChecklistsChecklistIdRouteRouteImport.update({
    id: '/$checklistId',
    path: '/$checklistId',
    getParentRoute: () => AuthChecklistsRouteRoute,
  } as any)
const AuthUsersUserIdIndexRoute = AuthUsersUserIdIndexRouteImport.update({
  id: '/users/$userId/',
  path: '/users/$userId/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthPropertiesCreateIndexRoute =
  AuthPropertiesCreateIndexRouteImport.update({
    id: '/create/',
    path: '/create/',
    getParentRoute: () => AuthPropertiesRouteRoute,
  } as any)
const AuthPropertiesPropertyIdIndexRoute =
  AuthPropertiesPropertyIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthPropertiesPropertyIdRouteRoute,
  } as any)
const AuthChecklistsCreateIndexRoute =
  AuthChecklistsCreateIndexRouteImport.update({
    id: '/create/',
    path: '/create/',
    getParentRoute: () => AuthChecklistsRouteRoute,
  } as any)
const AuthChecklistsChecklistIdItemsRouteRoute =
  AuthChecklistsChecklistIdItemsRouteRouteImport.update({
    id: '/items',
    path: '/items',
    getParentRoute: () => AuthChecklistsChecklistIdRouteRoute,
  } as any)
const AuthUsersUserIdEditIndexRoute =
  AuthUsersUserIdEditIndexRouteImport.update({
    id: '/users/$userId/edit/',
    path: '/users/$userId/edit/',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthPropertiesPropertyIdEditIndexRoute =
  AuthPropertiesPropertyIdEditIndexRouteImport.update({
    id: '/edit/',
    path: '/edit/',
    getParentRoute: () => AuthPropertiesPropertyIdRouteRoute,
  } as any)
const AuthChecklistsChecklistIdItemsIndexRoute =
  AuthChecklistsChecklistIdItemsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthChecklistsChecklistIdItemsRouteRoute,
  } as any)
const AuthChecklistsChecklistIdHistoryIndexRoute =
  AuthChecklistsChecklistIdHistoryIndexRouteImport.update({
    id: '/history/',
    path: '/history/',
    getParentRoute: () => AuthChecklistsChecklistIdRouteRoute,
  } as any)
const AuthChecklistsChecklistIdItemsItemIdRouteRoute =
  AuthChecklistsChecklistIdItemsItemIdRouteRouteImport.update({
    id: '/$itemId',
    path: '/$itemId',
    getParentRoute: () => AuthChecklistsChecklistIdItemsRouteRoute,
  } as any)
const AuthChecklistsChecklistIdItemsItemIdIndexRoute =
  AuthChecklistsChecklistIdItemsItemIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthChecklistsChecklistIdItemsItemIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/public': typeof PublicRoute
  '/checklists': typeof AuthChecklistsRouteRouteWithChildren
  '/persons': typeof AuthPersonsRouteRouteWithChildren
  '/properties': typeof AuthPropertiesRouteRouteWithChildren
  '/': typeof AuthIndexRoute
  '/checklists/$checklistId': typeof AuthChecklistsChecklistIdRouteRouteWithChildren
  '/properties/$propertyId': typeof AuthPropertiesPropertyIdRouteRouteWithChildren
  '/persons/create': typeof AuthPersonsCreateRoute
  '/account': typeof AuthAccountIndexRoute
  '/checklists/': typeof AuthChecklistsIndexRoute
  '/properties/': typeof AuthPropertiesIndexRoute
  '/users': typeof AuthUsersIndexRoute
  '/checklists/$checklistId/items': typeof AuthChecklistsChecklistIdItemsRouteRouteWithChildren
  '/checklists/create': typeof AuthChecklistsCreateIndexRoute
  '/properties/$propertyId/': typeof AuthPropertiesPropertyIdIndexRoute
  '/properties/create': typeof AuthPropertiesCreateIndexRoute
  '/users/$userId': typeof AuthUsersUserIdIndexRoute
  '/checklists/$checklistId/items/$itemId': typeof AuthChecklistsChecklistIdItemsItemIdRouteRouteWithChildren
  '/checklists/$checklistId/history': typeof AuthChecklistsChecklistIdHistoryIndexRoute
  '/checklists/$checklistId/items/': typeof AuthChecklistsChecklistIdItemsIndexRoute
  '/properties/$propertyId/edit': typeof AuthPropertiesPropertyIdEditIndexRoute
  '/users/$userId/edit': typeof AuthUsersUserIdEditIndexRoute
  '/checklists/$checklistId/items/$itemId/': typeof AuthChecklistsChecklistIdItemsItemIdIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/public': typeof PublicRoute
  '/persons': typeof AuthPersonsRouteRouteWithChildren
  '/': typeof AuthIndexRoute
  '/checklists/$checklistId': typeof AuthChecklistsChecklistIdRouteRouteWithChildren
  '/persons/create': typeof AuthPersonsCreateRoute
  '/account': typeof AuthAccountIndexRoute
  '/checklists': typeof AuthChecklistsIndexRoute
  '/properties': typeof AuthPropertiesIndexRoute
  '/users': typeof AuthUsersIndexRoute
  '/checklists/create': typeof AuthChecklistsCreateIndexRoute
  '/properties/$propertyId': typeof AuthPropertiesPropertyIdIndexRoute
  '/properties/create': typeof AuthPropertiesCreateIndexRoute
  '/users/$userId': typeof AuthUsersUserIdIndexRoute
  '/checklists/$checklistId/history': typeof AuthChecklistsChecklistIdHistoryIndexRoute
  '/checklists/$checklistId/items': typeof AuthChecklistsChecklistIdItemsIndexRoute
  '/properties/$propertyId/edit': typeof AuthPropertiesPropertyIdEditIndexRoute
  '/users/$userId/edit': typeof AuthUsersUserIdEditIndexRoute
  '/checklists/$checklistId/items/$itemId': typeof AuthChecklistsChecklistIdItemsItemIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/public': typeof PublicRoute
  '/_auth/checklists': typeof AuthChecklistsRouteRouteWithChildren
  '/_auth/persons': typeof AuthPersonsRouteRouteWithChildren
  '/_auth/properties': typeof AuthPropertiesRouteRouteWithChildren
  '/_auth/': typeof AuthIndexRoute
  '/_auth/checklists/$checklistId': typeof AuthChecklistsChecklistIdRouteRouteWithChildren
  '/_auth/properties/$propertyId': typeof AuthPropertiesPropertyIdRouteRouteWithChildren
  '/_auth/persons/create': typeof AuthPersonsCreateRoute
  '/_auth/account/': typeof AuthAccountIndexRoute
  '/_auth/checklists/': typeof AuthChecklistsIndexRoute
  '/_auth/properties/': typeof AuthPropertiesIndexRoute
  '/_auth/users/': typeof AuthUsersIndexRoute
  '/_auth/checklists/$checklistId/items': typeof AuthChecklistsChecklistIdItemsRouteRouteWithChildren
  '/_auth/checklists/create/': typeof AuthChecklistsCreateIndexRoute
  '/_auth/properties/$propertyId/': typeof AuthPropertiesPropertyIdIndexRoute
  '/_auth/properties/create/': typeof AuthPropertiesCreateIndexRoute
  '/_auth/users/$userId/': typeof AuthUsersUserIdIndexRoute
  '/_auth/checklists/$checklistId/items/$itemId': typeof AuthChecklistsChecklistIdItemsItemIdRouteRouteWithChildren
  '/_auth/checklists/$checklistId/history/': typeof AuthChecklistsChecklistIdHistoryIndexRoute
  '/_auth/checklists/$checklistId/items/': typeof AuthChecklistsChecklistIdItemsIndexRoute
  '/_auth/properties/$propertyId/edit/': typeof AuthPropertiesPropertyIdEditIndexRoute
  '/_auth/users/$userId/edit/': typeof AuthUsersUserIdEditIndexRoute
  '/_auth/checklists/$checklistId/items/$itemId/': typeof AuthChecklistsChecklistIdItemsItemIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/public'
    | '/checklists'
    | '/persons'
    | '/properties'
    | '/'
    | '/checklists/$checklistId'
    | '/properties/$propertyId'
    | '/persons/create'
    | '/account'
    | '/checklists/'
    | '/properties/'
    | '/users'
    | '/checklists/$checklistId/items'
    | '/checklists/create'
    | '/properties/$propertyId/'
    | '/properties/create'
    | '/users/$userId'
    | '/checklists/$checklistId/items/$itemId'
    | '/checklists/$checklistId/history'
    | '/checklists/$checklistId/items/'
    | '/properties/$propertyId/edit'
    | '/users/$userId/edit'
    | '/checklists/$checklistId/items/$itemId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/public'
    | '/persons'
    | '/'
    | '/checklists/$checklistId'
    | '/persons/create'
    | '/account'
    | '/checklists'
    | '/properties'
    | '/users'
    | '/checklists/create'
    | '/properties/$propertyId'
    | '/properties/create'
    | '/users/$userId'
    | '/checklists/$checklistId/history'
    | '/checklists/$checklistId/items'
    | '/properties/$propertyId/edit'
    | '/users/$userId/edit'
    | '/checklists/$checklistId/items/$itemId'
  id:
    | '__root__'
    | '/_auth'
    | '/login'
    | '/public'
    | '/_auth/checklists'
    | '/_auth/persons'
    | '/_auth/properties'
    | '/_auth/'
    | '/_auth/checklists/$checklistId'
    | '/_auth/properties/$propertyId'
    | '/_auth/persons/create'
    | '/_auth/account/'
    | '/_auth/checklists/'
    | '/_auth/properties/'
    | '/_auth/users/'
    | '/_auth/checklists/$checklistId/items'
    | '/_auth/checklists/create/'
    | '/_auth/properties/$propertyId/'
    | '/_auth/properties/create/'
    | '/_auth/users/$userId/'
    | '/_auth/checklists/$checklistId/items/$itemId'
    | '/_auth/checklists/$checklistId/history/'
    | '/_auth/checklists/$checklistId/items/'
    | '/_auth/properties/$propertyId/edit/'
    | '/_auth/users/$userId/edit/'
    | '/_auth/checklists/$checklistId/items/$itemId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
  PublicRoute: typeof PublicRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/public': {
      id: '/public'
      path: '/public'
      fullPath: '/public'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/properties': {
      id: '/_auth/properties'
      path: '/properties'
      fullPath: '/properties'
      preLoaderRoute: typeof AuthPropertiesRouteRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/persons': {
      id: '/_auth/persons'
      path: '/persons'
      fullPath: '/persons'
      preLoaderRoute: typeof AuthPersonsRouteRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/checklists': {
      id: '/_auth/checklists'
      path: '/checklists'
      fullPath: '/checklists'
      preLoaderRoute: typeof AuthChecklistsRouteRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/users/': {
      id: '/_auth/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthUsersIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/properties/': {
      id: '/_auth/properties/'
      path: '/'
      fullPath: '/properties/'
      preLoaderRoute: typeof AuthPropertiesIndexRouteImport
      parentRoute: typeof AuthPropertiesRouteRoute
    }
    '/_auth/checklists/': {
      id: '/_auth/checklists/'
      path: '/'
      fullPath: '/checklists/'
      preLoaderRoute: typeof AuthChecklistsIndexRouteImport
      parentRoute: typeof AuthChecklistsRouteRoute
    }
    '/_auth/account/': {
      id: '/_auth/account/'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthAccountIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/persons/create': {
      id: '/_auth/persons/create'
      path: '/create'
      fullPath: '/persons/create'
      preLoaderRoute: typeof AuthPersonsCreateRouteImport
      parentRoute: typeof AuthPersonsRouteRoute
    }
    '/_auth/properties/$propertyId': {
      id: '/_auth/properties/$propertyId'
      path: '/$propertyId'
      fullPath: '/properties/$propertyId'
      preLoaderRoute: typeof AuthPropertiesPropertyIdRouteRouteImport
      parentRoute: typeof AuthPropertiesRouteRoute
    }
    '/_auth/checklists/$checklistId': {
      id: '/_auth/checklists/$checklistId'
      path: '/$checklistId'
      fullPath: '/checklists/$checklistId'
      preLoaderRoute: typeof AuthChecklistsChecklistIdRouteRouteImport
      parentRoute: typeof AuthChecklistsRouteRoute
    }
    '/_auth/users/$userId/': {
      id: '/_auth/users/$userId/'
      path: '/users/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof AuthUsersUserIdIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/properties/create/': {
      id: '/_auth/properties/create/'
      path: '/create'
      fullPath: '/properties/create'
      preLoaderRoute: typeof AuthPropertiesCreateIndexRouteImport
      parentRoute: typeof AuthPropertiesRouteRoute
    }
    '/_auth/properties/$propertyId/': {
      id: '/_auth/properties/$propertyId/'
      path: '/'
      fullPath: '/properties/$propertyId/'
      preLoaderRoute: typeof AuthPropertiesPropertyIdIndexRouteImport
      parentRoute: typeof AuthPropertiesPropertyIdRouteRoute
    }
    '/_auth/checklists/create/': {
      id: '/_auth/checklists/create/'
      path: '/create'
      fullPath: '/checklists/create'
      preLoaderRoute: typeof AuthChecklistsCreateIndexRouteImport
      parentRoute: typeof AuthChecklistsRouteRoute
    }
    '/_auth/checklists/$checklistId/items': {
      id: '/_auth/checklists/$checklistId/items'
      path: '/items'
      fullPath: '/checklists/$checklistId/items'
      preLoaderRoute: typeof AuthChecklistsChecklistIdItemsRouteRouteImport
      parentRoute: typeof AuthChecklistsChecklistIdRouteRoute
    }
    '/_auth/users/$userId/edit/': {
      id: '/_auth/users/$userId/edit/'
      path: '/users/$userId/edit'
      fullPath: '/users/$userId/edit'
      preLoaderRoute: typeof AuthUsersUserIdEditIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/properties/$propertyId/edit/': {
      id: '/_auth/properties/$propertyId/edit/'
      path: '/edit'
      fullPath: '/properties/$propertyId/edit'
      preLoaderRoute: typeof AuthPropertiesPropertyIdEditIndexRouteImport
      parentRoute: typeof AuthPropertiesPropertyIdRouteRoute
    }
    '/_auth/checklists/$checklistId/items/': {
      id: '/_auth/checklists/$checklistId/items/'
      path: '/'
      fullPath: '/checklists/$checklistId/items/'
      preLoaderRoute: typeof AuthChecklistsChecklistIdItemsIndexRouteImport
      parentRoute: typeof AuthChecklistsChecklistIdItemsRouteRoute
    }
    '/_auth/checklists/$checklistId/history/': {
      id: '/_auth/checklists/$checklistId/history/'
      path: '/history'
      fullPath: '/checklists/$checklistId/history'
      preLoaderRoute: typeof AuthChecklistsChecklistIdHistoryIndexRouteImport
      parentRoute: typeof AuthChecklistsChecklistIdRouteRoute
    }
    '/_auth/checklists/$checklistId/items/$itemId': {
      id: '/_auth/checklists/$checklistId/items/$itemId'
      path: '/$itemId'
      fullPath: '/checklists/$checklistId/items/$itemId'
      preLoaderRoute: typeof AuthChecklistsChecklistIdItemsItemIdRouteRouteImport
      parentRoute: typeof AuthChecklistsChecklistIdItemsRouteRoute
    }
    '/_auth/checklists/$checklistId/items/$itemId/': {
      id: '/_auth/checklists/$checklistId/items/$itemId/'
      path: '/'
      fullPath: '/checklists/$checklistId/items/$itemId/'
      preLoaderRoute: typeof AuthChecklistsChecklistIdItemsItemIdIndexRouteImport
      parentRoute: typeof AuthChecklistsChecklistIdItemsItemIdRouteRoute
    }
  }
}

interface AuthChecklistsChecklistIdItemsItemIdRouteRouteChildren {
  AuthChecklistsChecklistIdItemsItemIdIndexRoute: typeof AuthChecklistsChecklistIdItemsItemIdIndexRoute
}

const AuthChecklistsChecklistIdItemsItemIdRouteRouteChildren: AuthChecklistsChecklistIdItemsItemIdRouteRouteChildren =
  {
    AuthChecklistsChecklistIdItemsItemIdIndexRoute:
      AuthChecklistsChecklistIdItemsItemIdIndexRoute,
  }

const AuthChecklistsChecklistIdItemsItemIdRouteRouteWithChildren =
  AuthChecklistsChecklistIdItemsItemIdRouteRoute._addFileChildren(
    AuthChecklistsChecklistIdItemsItemIdRouteRouteChildren,
  )

interface AuthChecklistsChecklistIdItemsRouteRouteChildren {
  AuthChecklistsChecklistIdItemsItemIdRouteRoute: typeof AuthChecklistsChecklistIdItemsItemIdRouteRouteWithChildren
  AuthChecklistsChecklistIdItemsIndexRoute: typeof AuthChecklistsChecklistIdItemsIndexRoute
}

const AuthChecklistsChecklistIdItemsRouteRouteChildren: AuthChecklistsChecklistIdItemsRouteRouteChildren =
  {
    AuthChecklistsChecklistIdItemsItemIdRouteRoute:
      AuthChecklistsChecklistIdItemsItemIdRouteRouteWithChildren,
    AuthChecklistsChecklistIdItemsIndexRoute:
      AuthChecklistsChecklistIdItemsIndexRoute,
  }

const AuthChecklistsChecklistIdItemsRouteRouteWithChildren =
  AuthChecklistsChecklistIdItemsRouteRoute._addFileChildren(
    AuthChecklistsChecklistIdItemsRouteRouteChildren,
  )

interface AuthChecklistsChecklistIdRouteRouteChildren {
  AuthChecklistsChecklistIdItemsRouteRoute: typeof AuthChecklistsChecklistIdItemsRouteRouteWithChildren
  AuthChecklistsChecklistIdHistoryIndexRoute: typeof AuthChecklistsChecklistIdHistoryIndexRoute
}

const AuthChecklistsChecklistIdRouteRouteChildren: AuthChecklistsChecklistIdRouteRouteChildren =
  {
    AuthChecklistsChecklistIdItemsRouteRoute:
      AuthChecklistsChecklistIdItemsRouteRouteWithChildren,
    AuthChecklistsChecklistIdHistoryIndexRoute:
      AuthChecklistsChecklistIdHistoryIndexRoute,
  }

const AuthChecklistsChecklistIdRouteRouteWithChildren =
  AuthChecklistsChecklistIdRouteRoute._addFileChildren(
    AuthChecklistsChecklistIdRouteRouteChildren,
  )

interface AuthChecklistsRouteRouteChildren {
  AuthChecklistsChecklistIdRouteRoute: typeof AuthChecklistsChecklistIdRouteRouteWithChildren
  AuthChecklistsIndexRoute: typeof AuthChecklistsIndexRoute
  AuthChecklistsCreateIndexRoute: typeof AuthChecklistsCreateIndexRoute
}

const AuthChecklistsRouteRouteChildren: AuthChecklistsRouteRouteChildren = {
  AuthChecklistsChecklistIdRouteRoute:
    AuthChecklistsChecklistIdRouteRouteWithChildren,
  AuthChecklistsIndexRoute: AuthChecklistsIndexRoute,
  AuthChecklistsCreateIndexRoute: AuthChecklistsCreateIndexRoute,
}

const AuthChecklistsRouteRouteWithChildren =
  AuthChecklistsRouteRoute._addFileChildren(AuthChecklistsRouteRouteChildren)

interface AuthPersonsRouteRouteChildren {
  AuthPersonsCreateRoute: typeof AuthPersonsCreateRoute
}

const AuthPersonsRouteRouteChildren: AuthPersonsRouteRouteChildren = {
  AuthPersonsCreateRoute: AuthPersonsCreateRoute,
}

const AuthPersonsRouteRouteWithChildren =
  AuthPersonsRouteRoute._addFileChildren(AuthPersonsRouteRouteChildren)

interface AuthPropertiesPropertyIdRouteRouteChildren {
  AuthPropertiesPropertyIdIndexRoute: typeof AuthPropertiesPropertyIdIndexRoute
  AuthPropertiesPropertyIdEditIndexRoute: typeof AuthPropertiesPropertyIdEditIndexRoute
}

const AuthPropertiesPropertyIdRouteRouteChildren: AuthPropertiesPropertyIdRouteRouteChildren =
  {
    AuthPropertiesPropertyIdIndexRoute: AuthPropertiesPropertyIdIndexRoute,
    AuthPropertiesPropertyIdEditIndexRoute:
      AuthPropertiesPropertyIdEditIndexRoute,
  }

const AuthPropertiesPropertyIdRouteRouteWithChildren =
  AuthPropertiesPropertyIdRouteRoute._addFileChildren(
    AuthPropertiesPropertyIdRouteRouteChildren,
  )

interface AuthPropertiesRouteRouteChildren {
  AuthPropertiesPropertyIdRouteRoute: typeof AuthPropertiesPropertyIdRouteRouteWithChildren
  AuthPropertiesIndexRoute: typeof AuthPropertiesIndexRoute
  AuthPropertiesCreateIndexRoute: typeof AuthPropertiesCreateIndexRoute
}

const AuthPropertiesRouteRouteChildren: AuthPropertiesRouteRouteChildren = {
  AuthPropertiesPropertyIdRouteRoute:
    AuthPropertiesPropertyIdRouteRouteWithChildren,
  AuthPropertiesIndexRoute: AuthPropertiesIndexRoute,
  AuthPropertiesCreateIndexRoute: AuthPropertiesCreateIndexRoute,
}

const AuthPropertiesRouteRouteWithChildren =
  AuthPropertiesRouteRoute._addFileChildren(AuthPropertiesRouteRouteChildren)

interface AuthRouteChildren {
  AuthChecklistsRouteRoute: typeof AuthChecklistsRouteRouteWithChildren
  AuthPersonsRouteRoute: typeof AuthPersonsRouteRouteWithChildren
  AuthPropertiesRouteRoute: typeof AuthPropertiesRouteRouteWithChildren
  AuthIndexRoute: typeof AuthIndexRoute
  AuthAccountIndexRoute: typeof AuthAccountIndexRoute
  AuthUsersIndexRoute: typeof AuthUsersIndexRoute
  AuthUsersUserIdIndexRoute: typeof AuthUsersUserIdIndexRoute
  AuthUsersUserIdEditIndexRoute: typeof AuthUsersUserIdEditIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthChecklistsRouteRoute: AuthChecklistsRouteRouteWithChildren,
  AuthPersonsRouteRoute: AuthPersonsRouteRouteWithChildren,
  AuthPropertiesRouteRoute: AuthPropertiesRouteRouteWithChildren,
  AuthIndexRoute: AuthIndexRoute,
  AuthAccountIndexRoute: AuthAccountIndexRoute,
  AuthUsersIndexRoute: AuthUsersIndexRoute,
  AuthUsersUserIdIndexRoute: AuthUsersUserIdIndexRoute,
  AuthUsersUserIdEditIndexRoute: AuthUsersUserIdEditIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
  PublicRoute: PublicRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
